### ISSUE TITLE
Forecast data privided as string instead of list

### ISSUE THREAD

**Issue by DirkMu** [hg1337/homeassistant-dwd#15]
I am using a trigger template in order to extract the foreacst data which I am using in my weather templeate. 

However, when I use this integration the service weather.get_forecast returns a string. HA expects a list. 

```
trigger:
  - platform: time_pattern
    hours: 0
    minutes: 0
  - platform: homeassistant
    event: start
  - platform: event
    event_type: event_template_reloaded
action:
  - service: weather.get_forecast
    target:
      entity_id: weather.heusweiler_2
    data: 
      type: daily
    response_variable: daily_weather
```
```
  - name: weather_forecast_daily
    unique_id: weather_forecast_daily
    state: "{{ now().isoformat() }}"
    attributes:
      forecast: "{{ daily_weather.forecast }}"
```

![image](https://github.com/hg1337/homeassistant-dwd/assets/53949754/d6c8a48e-feae-4f53-adfb-c8cf4bad4dad)
