### ISSUE TITLE
Weather forecast Determine the time yourself

### ISSUE THREAD

**Issue by klio-klio** [hg1337/homeassistant-dwd#16]
I want to know the weather forecast in 6 or 12 hours. Is this somehow possible?

**Comment by hg1337** [comment]
Generally, this is possible, independently of this integration. Therefore there is no dedicated functionality for this in this integration.

The forecast of weather entities is always returned as a list. Usually, index 0 is the current hour/day, which is how this integration does it. So if you take the hourly forecast list, the forecast at index 6 is the forecast for in 6 hours and at index 12 for in 12 hours.

What exactly do you want to do? Do you just want to display it? Do you want to use it in an automation? Depending on your use case, the method to achieve this is different. If you just want to display it, you can maybe find a 3rd party weather card that can exactly do that. Otherwise, creating a template sensor is probably the most universally applicable way. https://www.home-assistant.io/blog/2023/09/06/release-20239/#weather-forecast-service shows an example how to create a template sensor based on weather forecasts. You can also have a look at this video tutorial: https://www.home-assistant.io/integrations/template/#video-tutorial

A template sensor that returns this forecast for in 6 hours could e.g. look like that:

```yaml
- trigger:
    - platform: time_pattern
      minutes: "*"
    - platform: homeassistant
      event: start
    - platform: event
      event_type: event_template_reloaded
  action:
    - service: weather.get_forecast
      target:
        entity_id: weather.stuttgart_echterdingen
      data:
        type: hourly
      response_variable: forecast
  sensor:
    - name: weather_forecast_6_hours
      unique_id: weather_forecast_6_hours
      state: "{{ forecast.forecast[6].condition }}"
      attributes:
        forecast: "{{ forecast.forecast[6] }}"
```

I'm closing this, but feel free to ask further.
